name: githubCA
on: 
  push: 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code from the repository
      - name: Checkout
        uses: actions/checkout@v3
      
      # Install the Railway CLI
      - name: Install Railway
        run: npm i -g @railway/cli

      # Deploy the application using the Railway CLI
      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}

      # Send custom JSON data to a Slack workflow
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Custom JSON payload to send to Slack
          payload: |
             {
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "DipSA 56 CI/CD Submission",
                      "emoji": true
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Name:* Cheng YiYang "
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Email:* e1112937@u.nus.edu"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Metriculation:* A0269554N"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Repository:*"
                      },
                      {
                        "type": "plain_text",
                        "text": " ",
                        "emoji": true
                      },
                      {
                        "type": "mrkdwn",
                        "text": "${{github.event.repository.url}}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "This is a section block with a button."
                    },
                    "accessory": {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Go",
                        "emoji": true
                      },
                      "value": "click_me_123",
                      "url": "www.google.com",
                      "action_id": "button-action"
                    }
                  }
                ]
              }

        env:
          # Secret Slack Webhook URL
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
